-- CREATED by CHATGPT
-- Id's are auto generated by the database, so don't insert those manually

-- Insert sample planes
INSERT INTO plane (model, total_rows, seats_per_row) VALUES
('Boeing 737', 20, 6),
('Airbus A320', 25, 6);

-- Insert sample seats
INSERT INTO seat (seat_number, seat_letter, row_number, seat_type, is_next_to_window, is_next_to_aisle, extra_leg_room, is_available, plane_id) VALUES
('1', 'A', 1, 'Business', true, false, true, true, 1),
('1', 'B', 1, 'Business', false, true, true, true, 1),
('2', 'A', 2, 'Standard', true, false, false, true, 1),
('2', 'B', 2, 'Standard', false, true, false, false, 1),
('3', 'A', 3, 'Standard', true, false, false, true, 2),
('3', 'B', 3, 'Standard', false, true, false, false, 2);

-- Insert sample flights
INSERT INTO flight (flight_number, destination, departure_date, departure_time, arrival_date, arrival_time, duration, price, plane_id) VALUES
('FL123', 'New York', '2025-04-01', '08:00:00', '2025-04-01', '12:00:00', 240, 500.00, 1),
('FL456', 'London', '2025-04-02', '10:00:00', '2025-04-02', '14:30:00', 270, 450.00, 2);

-- Insert sample bookings
INSERT INTO booking (passenger_name, passenger_email, passenger_phone, booking_time, flight_id) VALUES
('Alice Johnson', 'alice@example.com', '1234567890', '2025-03-01T10:00:00', 1),
('Bob Smith', 'bob@example.com', '9876543210', '2025-03-02T11:00:00', 2);

-- Insert booking-seat relationships
INSERT INTO booking_seat (booking_id, seat_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4);
